import 'package:hive/hive.dart';
import 'package:movies/features/layout/home/domain/entities/movie_entity.dart';

// This will be generated by build_runner
part 'movie_model.g.dart';

@HiveType(typeId: 0) // Unique typeId for this class
class MovieModel extends MovieEntity {
  MovieModel({
    required super.id,
    required super.rating,
    required super.mediumCoverImage,
  });

  factory MovieModel.fromJson(Map<String, dynamic> json) {
    return MovieModel(
      id: json["id"] ?? 0,
      rating: json["rating"] ?? 0,
      mediumCoverImage: json["medium_cover_image"] ??
          "https://t4.ftcdn.net/jpg/04/00/24/31/360_F_400243185_BOxON3h9avMUX10RsDkt3pJ8iQx72kS3.jpg",
    );
  }

  // Optional: If you need to convert back to JSON
  @override
  Map<String, dynamic> toJson() => {
        "id": id,
        "rating": rating,
        "medium_cover_image": mediumCoverImage,
      };


}
